### ISSUE TITLE
Can‘t find BertFlowDelta operation

### ISSUE THREAD

**Issue by ZhengDeQuan** [MiuLab/FlowDelta#2]
In the paper ，
hL = LN(hL−1 + SA(hL−1) + FlowDelta(hL−1))
This is the bert flowDelta operation, but I didn't find it in the code.

**Comment by ady-yu** [comment]
> In the paper ，
> hL = LN(hL−1 + SA(hL−1) + FlowDelta(hL−1))
> This is the bert flowDelta operation, but I didn't find it in the code.

Have you find it? I dont find it either.
