### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by chenQ1114** [MiuLab/FlowDelta#3]
When I run the train_coqa.sh in the BerfFlowDelta, I got such error:

  File "run_coqa.py", line 1371, in main
    f1 = run_dev(model, eval_dataloader, evaluator)
  File "run_coqa.py", line 1302, in run_dev
    ignore_write=True)
  File "run_coqa.py", line 760, in write_predictions
    scores_diff_json[example.qas_id] = (score_diff, final_text, best_non_null_entry.text)
   AttributeError: 'NoneType' object has no attribute 'text'

**Comment by exe1023** [comment]
It seems like that the best_non_null_entry accidentally became None. (It may happen when all predictions are None)
I have fixed the problem.
