### ISSUE TITLE
I can't get the results in the paper.

### ISSUE THREAD

**Issue by menggehe** [MiuLab/FlowDelta#4]
hello,author!
I can't get the results in the paper, the F1 score i get is about 56 on QuAC. Can you tell me your config?
Maybe you can contact me by email : 1056147394@qq.com. Thank you！

**Comment by pengshuang** [comment]
Me too

**Comment by exe1023** [comment]
I am sorry for that.
I think I messed up when cleaning the released code, since in my preliminary experiments, even the vanilla BERT should have > 60 f1 score on QuAC.
I will debug the code as soon as possible, and if you only want to inference the model, you can check out our codalab for pretrained model and inference detail.

**Comment by menggehe** [comment]
> I am sorry for that.
> I think I messed up when cleaning the released code, since in my preliminary experiments, even the vanilla BERT should have > 60 f1 score on QuAC.
> I will debug the code as soon as possible, and if you only want to inference the model, you can check out our codalab for pretrained model and inference detail.

Thank you! I look forward to your reply again.

**Comment by exe1023** [comment]
Hi, I have fixed the problem, and now you can have around 67 f1 score on the dev set of QuAC.
Actually it is not the bug.
When I tested the code on my personal PC with only GTX 1070 card, I restricted the maximum batch size to 4, and forgot to set it back to 12.

**Comment by menggehe** [comment]
> Hi, I have fixed the problem, and now you can have around 67 f1 score on the dev set of QuAC.
> Actually it is not the bug.
> When I tested the code on my personal PC with only GTX 1070 card, I restricted the maximum batch size to 4, and forgot to set it back to 12.

Thank you very much! You are very efficient!
