### ISSUE TITLE
Is it allowed that to use previous real answer in the prediction process ?

### ISSUE THREAD

**Issue by pengshuang** [MiuLab/FlowDelta#5]
Hi, 

I have one question about the prediction process.

Here your code uses the previous real question and original answer as the context information in the evaluation process. 
https://github.com/MiuLab/FlowDelta/blob/0b42704988ef548824c1be33e8e6ae8ea8238129/BertFlowDelta/run_quac.py#L155

Is it allowed ?

**Comment by exe1023** [comment]
Yes, it is allowed in both QuAC and CoQA datasets. 
When you predict the question in turn t, you can use ground truth answer from trun 1 to trun (t-1).

**Comment by pengshuang** [comment]
thanks
