### ISSUE TITLE
Batch Logic in BertFlowDelta

### ISSUE THREAD

**Issue by pengshuang** [MiuLab/FlowDelta#7]
Hi,

https://github.com/MiuLab/FlowDelta/blob/845aa8cc2a6804a3f663cfbe8ffdf09710323c44/BertFlowDelta/run_quac.py#L831

I see that in the preprocess of BertFlowDelta, the original code take a slide window mechanism to handle the documents that are longer than the maximum sequence length.

As a result, a long document will be processed into 2 or 3 shorter chunks. If so, is the context features still useful ?

**Comment by pengshuang** [comment]
https://github.com/MiuLab/FlowDelta/blob/845aa8cc2a6804a3f663cfbe8ffdf09710323c44/BertFlowDelta/run_quac.py#L277

https://github.com/MiuLab/FlowDelta/blob/845aa8cc2a6804a3f663cfbe8ffdf09710323c44/BertFlowDelta/run_quac.py#L381

I think that you are not allowed to use slide window here.

What's you idea ?

**Comment by exe1023** [comment]
When I implemented the context feature, I assumed that for any turn t of the dialog, the answer of the subsequent few turns (e.g. t+1) would not jump too far away.
In other words, I assume the subsequent few turns will be in the same document chunk as the current turn.
The reason to do this assumption is that I was lazy and did not have enough time to fix this part when I was writing the paper.
I think if you fixed this problem, you will have some improvement.

**Comment by pengshuang** [comment]
I see, thanks
